/**
 * RunContext + TokenCounter: Real Token Anchoring
 *
 * Character-based token estimates (len/3.5) drift 20%+ from real API counts
 * under heavy tool-result traffic. That drift makes compaction thresholds
 * fire too early or too late. This module anchors estimates on the actual
 * token counts reported by the LLM provider after each API call.
 *
 * Scope: minimal wrapper around provider-reported usage. Does NOT duplicate
 * Mastra's internal iteration/scratchpad tracking — Mastra's RequestContext
 * already covers that surface.
 */

export class TokenCounter {
  private charCount: number = 0;
  private apiReportedInput: number = 0;
  private apiReportedOutput: number = 0;

  addChars(n: number): void {
    this.charCount += n;
  }

  /** Record actual token usage from an API response. */
  recordApiUsage(inputTokens: number, outputTokens: number): void {
    this.apiReportedInput = inputTokens;
    this.apiReportedOutput += outputTokens;
  }

  /** Best-available estimate of current context size in tokens. */
  estimate(): number {
    if (this.apiReportedInput > 0) return this.apiReportedInput;
    return Math.ceil(this.charCount / 3.5);
  }

  /** Cumulative output tokens generated by the model so far. */
  totalOutput(): number {
    return this.apiReportedOutput;
  }

  /** Input tokens reported by the API on the most recent call. */
  lastApiInput(): number {
    return this.apiReportedInput;
  }
}

export interface RunContext {
  readonly query: string;
  readonly tokenCounter: TokenCounter;
  readonly startTime: number;
  /** Whether full compaction has already run this session. */
  compactedThisSession: boolean;
  /**
   * Input token count from the most recent API response. Mirrors
   * tokenCounter.lastApiInput() for quick access by threshold checks.
   */
  lastApiInputTokens: number;
}

export function createRunContext(query: string): RunContext {
  return {
    query,
    tokenCounter: new TokenCounter(),
    startTime: Date.now(),
    compactedThisSession: false,
    lastApiInputTokens: 0,
  };
}

/** Update the RunContext after an API response. */
export function recordApiUsage(
  ctx: RunContext,
  inputTokens: number,
  outputTokens: number,
): void {
  ctx.tokenCounter.recordApiUsage(inputTokens, outputTokens);
  ctx.lastApiInputTokens = inputTokens;
}
