/**
 * Deterministic continuous-double-auction (CDA) limit-order-book matching engine.
 *
 * Order-level, pure, and clock-free: matching is driven entirely by a monotonic
 * internal sequence counter, so an identical submit/cancel stream always yields
 * an identical transaction stream and book state. Built for order-level backtest
 * realism (queue position, walk-the-book slippage) in execution-algo validation,
 * NOT as a statistical price generator.
 *
 * Semantics:
 *   - Price-time priority. Bids rank by highest price then earliest arrival;
 *     asks rank by lowest price then earliest arrival.
 *   - A marketable incoming order walks the opposite side, taking each resting
 *     ("maker") order at the MAKER's price until it is filled or the book stops
 *     crossing. Any unfilled remainder of a LIMIT order rests; a MARKET order's
 *     remainder is discarded (no resting, no price protection).
 *   - Partial fills reduce the resting order's remaining quantity in place.
 *   - Cancels remove a resting order by id.
 *
 * The engine emits `Transaction`s and can materialize an aggregated
 * `BookSnapshot` at any point.
 */

export type LobSide = "buy" | "sell";

export interface LobOrder {
  /** Caller-unique order id. */
  id: string;
  side: LobSide;
  /** Limit price. Ignored for market orders. */
  price: number;
  /** Order quantity (base units). Must be > 0. */
  quantity: number;
  /** "limit" (default) rests any remainder; "market" discards it. */
  type?: "limit" | "market";
}

export interface Transaction {
  /** Resting order that provided liquidity. */
  makerId: string;
  /** Incoming order that consumed liquidity. */
  takerId: string;
  /** Execution price = the maker's resting price. */
  price: number;
  /** Filled quantity. */
  quantity: number;
  /** Aggressor side (the taker's side). */
  aggressor: LobSide;
  /** Monotonic trade sequence number. */
  sequence: number;
}

export interface BookLevel {
  price: number;
  /** Aggregate resting quantity at this price. */
  quantity: number;
  /** Number of distinct resting orders at this price. */
  orderCount: number;
}

export interface BookSnapshot {
  /** Bid levels, best (highest price) first. */
  bids: BookLevel[];
  /** Ask levels, best (lowest price) first. */
  asks: BookLevel[];
}

interface RestingOrder {
  id: string;
  side: LobSide;
  price: number;
  quantity: number;
  /** Arrival sequence for time priority. */
  seq: number;
}

/**
 * A single-symbol continuous-double-auction order book.
 *
 * Not thread-safe by design (single-threaded, deterministic replay). All
 * mutation happens through `submit` / `cancel`.
 */
export class OrderBook {
  /** Bids kept best-first: highest price, then earliest seq. */
  private bids: RestingOrder[] = [];
  /** Asks kept best-first: lowest price, then earliest seq. */
  private asks: RestingOrder[] = [];
  private arrivalSeq = 0;
  private tradeSeq = 0;

  /**
   * Submit a limit or market order. Matches against the opposite side under
   * price-time priority, then rests any limit remainder.
   *
   * @returns the transactions generated by this order, in execution order.
   */
  submit(order: LobOrder): Transaction[] {
    if (order.quantity <= 0) return [];
    const isMarket = order.type === "market";
    const seq = this.arrivalSeq++;
    let remaining = order.quantity;
    const transactions: Transaction[] = [];

    const book = order.side === "buy" ? this.asks : this.bids;

    while (remaining > 0 && book.length > 0) {
      const maker = book[0]!;
      const crosses = isMarket
        ? true
        : order.side === "buy"
          ? order.price >= maker.price
          : order.price <= maker.price;
      if (!crosses) break;

      const fill = Math.min(remaining, maker.quantity);
      transactions.push({
        makerId: maker.id,
        takerId: order.id,
        price: maker.price,
        quantity: fill,
        aggressor: order.side,
        sequence: this.tradeSeq++,
      });
      remaining -= fill;
      maker.quantity -= fill;
      if (maker.quantity <= 0) book.shift();
    }

    if (remaining > 0 && !isMarket) {
      this.insert({ id: order.id, side: order.side, price: order.price, quantity: remaining, seq });
    }

    return transactions;
  }

  /**
   * Cancel a resting order by id.
   * @returns true if an order was removed.
   */
  cancel(id: string): boolean {
    for (const book of [this.bids, this.asks]) {
      const idx = book.findIndex((o) => o.id === id);
      if (idx !== -1) {
        book.splice(idx, 1);
        return true;
      }
    }
    return false;
  }

  /** Best bid price, or undefined when the bid side is empty. */
  bestBid(): number | undefined {
    return this.bids[0]?.price;
  }

  /** Best ask price, or undefined when the ask side is empty. */
  bestAsk(): number | undefined {
    return this.asks[0]?.price;
  }

  /** Best-ask minus best-bid, or undefined when either side is empty. */
  spread(): number | undefined {
    const bid = this.bestBid();
    const ask = this.bestAsk();
    if (bid === undefined || ask === undefined) return undefined;
    return ask - bid;
  }

  /**
   * Aggregate the resting book into price levels, best-first.
   * @param depth optional cap on the number of levels returned per side.
   */
  snapshot(depth?: number): BookSnapshot {
    return {
      bids: aggregate(this.bids, depth),
      asks: aggregate(this.asks, depth),
    };
  }

  /** Insert a resting order at its price-time-priority position. */
  private insert(order: RestingOrder): void {
    const book = order.side === "buy" ? this.bids : this.asks;
    let lo = 0;
    let hi = book.length;
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      if (higherPriority(order, book[mid]!)) hi = mid;
      else lo = mid + 1;
    }
    book.splice(lo, 0, order);
  }
}

/** True when `a` outranks `b` under price-time priority for its side. */
function higherPriority(a: RestingOrder, b: RestingOrder): boolean {
  if (a.price !== b.price) {
    return a.side === "buy" ? a.price > b.price : a.price < b.price;
  }
  return a.seq < b.seq;
}

/** Collapse a priority-sorted resting book into aggregated price levels. */
function aggregate(book: RestingOrder[], depth?: number): BookLevel[] {
  const levels: BookLevel[] = [];
  for (const o of book) {
    const last = levels[levels.length - 1];
    if (last && last.price === o.price) {
      last.quantity += o.quantity;
      last.orderCount += 1;
    } else {
      if (depth !== undefined && levels.length >= depth) break;
      levels.push({ price: o.price, quantity: o.quantity, orderCount: 1 });
    }
  }
  return levels;
}
