/**
 * Backtest Types
 *
 * Core type definitions for backtesting strategies.
 */

import type { SystematicBacktestMetadata } from "../infra/domain/systematic/types.ts";

// ============================================================================
// OHLC Data
// ============================================================================

/**
 * OHLC (Open-High-Low-Close) candlestick data.
 * This is the basic price data structure used in backtesting.
 */
export interface OHLC {
  /** Candle open time (Unix timestamp in milliseconds) */
  timestamp: number;

  /** Opening price */
  open: number;

  /** Highest price during the candle period */
  high: number;

  /** Lowest price during the candle period */
  low: number;

  /** Closing price */
  close: number;

  /** Trading volume */
  volume: number;
}

// ============================================================================
// Signals
// ============================================================================

/**
 * Signal type enumeration.
 */
export type SignalType = "BUY" | "SELL" | "HOLD";

/**
 * Trading signal generated by a strategy.
 */
export interface Signal {
  /** Type of signal */
  type: SignalType;

  /** Price at which the signal was generated */
  price: number;

  /** Unix timestamp when the signal was generated */
  timestamp: number;

  /** Human-readable explanation for the signal */
  reason: string;

  /** Grid level index (0-based) for grid/DCA strategies. When set, the engine allows multiple concurrent positions. */
  gridLevel?: number;

  /** Maximum simultaneous grid positions allowed. Only used when gridLevel is set. Defaults to 1. */
  maxPositions?: number;
}

// ============================================================================
// Indicator State
// ============================================================================

/**
 * Pre-calculated indicator values for a specific bar.
 * Strategies use this to access indicator values without recalculating.
 */
export interface IndicatorState {
  // Simple Moving Averages
  sma20?: number | null;
  sma50?: number | null;
  sma200?: number | null;

  // Exponential Moving Averages
  ema12?: number | null;
  ema26?: number | null;
  ema50?: number | null;

  // RSI
  rsi14?: number | null;
  rsi14Prev?: number | null; // Previous RSI value for crossover detection

  // ATR
  atr14?: number | null;

  // Bollinger Bands
  bbUpper?: number | null;
  bbMiddle?: number | null;
  bbLower?: number | null;
  bbWidth?: number | null;

  // MACD
  macdLine?: number | null;
  macdSignal?: number | null;
  macdHistogram?: number | null;

  // VWAP
  vwap?: number | null;

  // Volume analysis
  volumeAvg20?: number | null;
  volumeRatio?: number | null; // Current volume / average volume

  // Support/Resistance levels (detected)
  nearestSupport?: number | null;
  nearestResistance?: number | null;
  supportStrength?: number | null;
  resistanceStrength?: number | null;

  // Allow additional custom indicators.
  // Strategies can request custom indicators via getRequiredIndicators() that will not be
  // pre-calculated by the engine -- they must be computed by the strategy itself
  // during generateSignal().
  [key: string]: number | null | undefined;
}

// ============================================================================
// Equity Tracking
// ============================================================================

/**
 * A point on the equity curve representing portfolio value at a moment in time.
 */
export interface EquityPoint {
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Portfolio value at this point */
  equity: number;
}

// ============================================================================
// Closed Trades
// ============================================================================

/**
 * A completed trade with entry and exit information.
 */
export interface ClosedTrade {
  /** Unique trade identifier */
  id: string;
  /** Trading pair (e.g., "BTCUSDT") */
  symbol: string;
  /** Trade direction */
  side: "long" | "short";
  /** Entry price */
  entryPrice: number;
  /** Exit price */
  exitPrice: number;
  /** Position size in base asset */
  quantity: number;
  /** Entry timestamp */
  entryTime: number;
  /** Exit timestamp */
  exitTime: number;
  /** Realized profit/loss in quote currency */
  pnl: number;
  /** Realized profit/loss as percentage */
  pnlPercent: number;
  /** Trading fees paid */
  fees: number;
}

// ============================================================================
// Backtest Metrics
// ============================================================================

/**
 * Comprehensive backtest performance metrics.
 */
export interface BacktestMetrics {
  // Return Metrics
  /** Total percentage return */
  totalReturn: number;
  /** Annualized return percentage */
  annualizedReturn: number;
  /** Compound Annual Growth Rate */
  cagr: number;

  // Risk Metrics
  /** Maximum peak-to-trough decline percentage */
  maxDrawdown: number;
  /** Sharpe ratio (risk-adjusted return) */
  sharpeRatio: number;
  /** Sortino ratio (downside risk-adjusted return) */
  sortinoRatio: number;
  /** Annualized volatility (standard deviation of returns) */
  volatility: number;
  /** Calmar ratio (return/drawdown) */
  calmarRatio: number;

  // Trade Metrics
  /** Total number of trades */
  totalTrades: number;
  /** Number of winning trades */
  winningTrades: number;
  /** Number of losing trades */
  losingTrades: number;
  /** Percentage of winning trades */
  winRate: number;
  /** Gross profit / gross loss */
  profitFactor: number;
  /** Average P&L per trade */
  averageTrade: number;
  /** Average winning trade P&L */
  averageWin: number;
  /** Average losing trade P&L */
  averageLoss: number;
  /** Expected value per trade */
  expectancy: number;
  /** Longest winning streak */
  maxConsecutiveWins: number;
  /** Longest losing streak */
  maxConsecutiveLosses: number;

  /** Initial portfolio value */
  initialValue: number;

  /** Final portfolio value */
  finalValue: number;

  /** Total profit/loss in quote currency */
  totalPnl: number;

  /** Net profit after fees */
  netProfit: number;

  /** Total fees paid */
  totalFees: number;

  /** Average trade duration in hours */
  avgTradeDuration: number;

  /** Maximum drawdown duration in days */
  maxDrawdownDuration: number;

  // Engine-specific extended metrics (optional)
  /** Total gross profit from winning trades */
  grossProfit?: number;
  /** Total gross loss from losing trades */
  grossLoss?: number;
  /** Largest single winning trade */
  largestWin?: number;
  /** Largest single losing trade */
  largestLoss?: number;
  /** Average holding period in hours */
  avgHoldingPeriod?: number;
  /** Average holding period for winning trades */
  avgWinHoldingPeriod?: number;
  /** Average holding period for losing trades */
  avgLossHoldingPeriod?: number;
  /** Total commission paid */
  totalCommission?: number;
  /** Commission as percentage of initial capital */
  commissionPct?: number;

  // Extended reporting metrics (optional, backward-compatible)
  /**
   * Tail ratio = 95th-percentile return / |5th-percentile return|. A value > 1
   * means the right tail (upside) is fatter than the left tail. Null/absent
   * when fewer than ~20 return observations.
   */
  tailRatio?: number;
  /**
   * Realized turnover. Average traded notional / equity per period (one-way).
   * Surfaced from the engine's position/trade record. Absent when positions
   * are not tracked per bar.
   */
  realizedTurnover?: number;
  /**
   * Rolling annualized Sharpe over a fixed window (default 63 periods).
   * Length = returns.length - window + 1. Empty when the series is shorter
   * than the window.
   */
  rollingSharpe?: number[];
  /**
   * Rolling beta of strategy returns against a benchmark return series, same
   * window as rollingSharpe. Null when no benchmark was provided.
   */
  rollingBeta?: number[] | null;
  /**
   * Top-N discrete drawdown episodes extracted from the equity curve, ranked
   * by depth (deepest first).
   */
  drawdownPeriods?: DrawdownPeriod[];
}

/**
 * A discrete drawdown episode on the equity curve: from a peak, down to a
 * trough, and back up to (or above) the prior peak (or end of series).
 */
export interface DrawdownPeriod {
  /** Index of the peak that started the drawdown. */
  startIdx: number;
  /** Index of the lowest equity point within the episode. */
  troughIdx: number;
  /**
   * Index at which equity recovered to the prior peak. Equals the last index
   * of the series when the episode never fully recovered.
   */
  endIdx: number;
  /** Drawdown depth as a positive percentage (peak-to-trough). */
  depth: number;
  /** Episode length in bars (endIdx - startIdx). */
  lengthBars: number;
}

// ============================================================================
// Backtest Configuration
// ============================================================================

/**
 * Configuration for running a backtest
 */
export interface BacktestConfig {
  /** Strategy ID */
  strategyId: string;

  /** Trading pair (e.g., "BTCUSDT") */
  symbol: string;

  /** Timeframe for candles (e.g., "4h", "1h", "15m") */
  timeframe: string;

  /** Number of days to backtest */
  days: number;

  /** Initial capital in USDT */
  initialCapital: number;

  /** Position size as percentage of capital (0-100) */
  positionSizePercent: number;

  /** Whether to compound profits */
  compounding: boolean;

  /** Trading fees percentage (e.g., 0.1 for 0.1%) */
  feePercent: number;

  /** Slippage percentage to simulate (e.g., 0.05 for 0.05%) */
  slippagePercent: number;

  /** Named simulation realism profile */
  simulationProfile?: "baseline" | "realistic" | "conservative";

  /** Execution lag in whole bars */
  executionLagBars?: number;

  /** Half-spread cost in basis points */
  spreadBps?: number;

  /** Additional market-impact cost in basis points */
  marketImpactBps?: number;
}

/**
 * Default backtest configuration
 */
export const DEFAULT_BACKTEST_CONFIG: Omit<BacktestConfig, "strategyId" | "symbol"> = {
  timeframe: "4h",
  days: 90,
  initialCapital: 10000,
  positionSizePercent: 10,
  compounding: false,
  feePercent: 0.1,
  slippagePercent: 0.05,
  simulationProfile: "realistic",
  executionLagBars: 1,
  spreadBps: 2,
  marketImpactBps: 1,
};

// ============================================================================
// Backtest Trade (Extended)
// ============================================================================

/**
 * A single trade in backtest history with extended details
 */
export interface BacktestTrade {
  /** Trade identifier */
  id: string;

  /** Entry timestamp (ISO string) */
  entryTime: string;

  /** Exit timestamp (ISO string) */
  exitTime: string;

  /** Entry price */
  entryPrice: number;

  /** Exit price */
  exitPrice: number;

  /** Position size in base asset */
  quantity: number;

  /** Position size in USDT */
  positionValue: number;

  /** Direction of trade */
  side: "LONG" | "SHORT";

  /** Profit/Loss in USDT */
  pnl: number;

  /** Profit/Loss percentage */
  pnlPercent: number;

  /** Fees paid in USDT */
  fees: number;

  /** Reason for exit */
  exitReason: "TP1" | "TP2" | "TP3" | "STOP" | "SIGNAL" | "END_OF_TEST";

  /** Strategy signals at entry */
  entrySignals?: Record<string, unknown>;
}

// ============================================================================
// Backtest Result
// ============================================================================

/**
 * Complete result from a backtest run
 */
export interface BacktestResult {
  /** Unique identifier for this backtest */
  id: string;

  /** Strategy name */
  strategyName: string;

  /** Configuration used for this backtest */
  config: BacktestConfig;

  /** Performance metrics */
  metrics: BacktestMetrics;

  /** Trade history */
  trades: BacktestTrade[];

  /** Equity curve (timestamp -> equity value) */
  equityCurve: EquityPoint[];

  /** Drawdown curve (timestamp -> drawdown percentage) */
  drawdownCurve: Array<{ timestamp: number; drawdown: number }>;

  /** Start date of backtest period */
  startDate: string;

  /** End date of backtest period */
  endDate: string;

  /** Execution time in milliseconds */
  executionTime: number;

  /** Timestamp when backtest was run */
  createdAt: string;

  /** Any warnings generated during backtest */
  warnings: string[];

  /** Optional systematic research metadata for reproducibility and promotion gating */
  systematic?: SystematicBacktestMetadata;
}

// ============================================================================
// Optimization Types
// ============================================================================

/**
 * Parameter range for optimization
 */
export interface ParameterRange {
  /** Parameter name */
  name: string;

  /** Minimum value */
  min: number;

  /** Maximum value */
  max: number;

  /** Step size */
  step: number;
}

/**
 * A specific set of parameter values
 */
export interface ParameterSet {
  [paramName: string]: number;
}

/**
 * Result from parameter optimization
 */
export interface OptimizationResult {
  /** Strategy being optimized */
  strategyId: string;

  /** Symbol tested on */
  symbol: string;

  /** Timeframe used */
  timeframe: string;

  /** Best parameters found */
  bestParameters: ParameterSet;

  /** Best metrics achieved */
  bestMetrics: BacktestMetrics;

  /** Top parameter combinations */
  topCombinations: Array<{
    parameters: ParameterSet;
    metrics: BacktestMetrics;
    rank: number;
  }>;

  /** Total combinations tested */
  totalCombinations: number;

  /** Execution time in milliseconds */
  executionTime: number;

  /** Timestamp when optimization was run */
  createdAt: string;
}

// ============================================================================
// Comparison Types
// ============================================================================

/**
 * Result from comparing multiple backtests
 */
export interface ComparisonResult {
  /** Symbol compared on */
  symbol: string;

  /** Timeframe used */
  timeframe: string;

  /** Period compared */
  period: { startDate: string; endDate: string };

  /** Individual backtest results */
  results: BacktestResult[];

  /** Strategy rankings by different metrics */
  rankings: {
    byReturn: StrategyRanking[];
    byWinRate: StrategyRanking[];
    bySharpe: StrategyRanking[];
    byDrawdown: StrategyRanking[];
  };

  /** Best overall strategy (balanced score) */
  bestOverall: string;

  /** Timestamp when comparison was run */
  createdAt: string;
}

/**
 * Strategy ranking entry
 */
export interface StrategyRanking {
  strategyId: string;
  strategyName: string;
  value: number;
  rank: number;
}

// ============================================================================
// Engine-Specific Types
// ============================================================================

/**
 * Position sizing mode for determining trade size.
 */
export type PositionSizingMode =
  | "FIXED_AMOUNT" // Use fixed dollar amount
  | "FIXED_PERCENT" // Use percentage of current equity
  | "KELLY" // Kelly criterion (requires win rate/avg win/loss)
  | "ALL_IN"; // Use 95% of available capital

/**
 * Kelly criterion parameters for position sizing.
 */
export interface KellyParams {
  /** Historical win rate (0-1) */
  winRate: number;
  /** Average winning trade return */
  avgWin: number;
  /** Average losing trade return (positive number) */
  avgLoss: number;
  /** Fraction multiplier (default 0.5 for half-Kelly) */
  fractionMultiplier?: number;
}

/**
 * Parameters for configuring a backtest run (engine format).
 */
export interface BacktestParams {
  /** Starting capital for the backtest */
  initialCapital: number;

  /**
   * Bar interval of the series being tested ("1m", "1h", "4h", "1d", ...).
   *
   * Required because it sets the annualization factor for Sharpe, Sortino and
   * volatility. Without it the metrics layer annualized everything at 365, as
   * though every bar were a calendar day, which on the default 4h bars
   * understates Sharpe by sqrt(2190/365) = 2.45x and on 1h bars by 4.9x.
   */
  timeframe: string;

  /** Position sizing mode */
  positionSizing: PositionSizingMode;

  /** Fixed amount to use per trade (for FIXED_AMOUNT mode) */
  fixedAmount?: number;

  /** Percentage of equity to use per trade (for FIXED_PERCENT mode, 0-1) */
  fixedPercent?: number;

  /** Commission rate as decimal (e.g., 0.001 = 0.1%) */
  commissionRate: number;

  /** Slippage rate as decimal (e.g., 0.0005 = 0.05%) */
  slippageRate: number;

  /** Signal execution lag in whole bars */
  executionLagBars?: number;

  /** Half-spread cost as decimal (e.g., 0.0002 = 2 bps) */
  spreadRate?: number;

  /** Additional market-impact cost as decimal */
  marketImpactRate?: number;

  /** Whether to allow short positions */
  allowShorts: boolean;

  /** Maximum drawdown before stopping (as decimal, e.g., 0.25 = 25%) */
  maxDrawdown?: number;

  /** Kelly criterion parameters (required if positionSizing is KELLY) */
  kelly?: KellyParams;
}

/**
 * Default backtest parameters.
 */
export const DEFAULT_BACKTEST_PARAMS: BacktestParams = {
  initialCapital: 10000,
  timeframe: "4h",
  positionSizing: "FIXED_PERCENT",
  fixedPercent: 0.1, // 10% of equity
  commissionRate: 0.001, // 0.1%
  slippageRate: 0.0005, // 0.05%
  executionLagBars: 0,
  spreadRate: 0,
  marketImpactRate: 0,
  allowShorts: false,
};

/**
 * Active position in the backtest engine.
 */
export interface Position {
  /** Unique position identifier */
  id: string;

  /** Position side */
  side: "LONG" | "SHORT";

  /** Entry price after slippage */
  entryPrice: number;

  /** Entry timestamp */
  entryTime: number;

  /** Entry bar index */
  entryBarIndex: number;

  /** Position quantity (units/shares) */
  quantity: number;

  /** Commission paid on entry */
  entryCommission: number;

  /** Stop loss price (if set) */
  stopLoss?: number;

  /** Take profit price (if set) */
  takeProfit?: number;

  /** Current unrealized P&L */
  unrealizedPnL: number;

  /** Grid level index (0-based) for grid/DCA positions */
  gridLevel?: number;
}

/**
 * Completed trade record for engine.
 */
export interface Trade {
  /** Unique trade identifier */
  id: string;

  /** Trade side */
  side: "LONG" | "SHORT";

  /** Entry price after slippage */
  entryPrice: number;

  /** Entry timestamp */
  entryTime: number;

  /** Exit price after slippage */
  exitPrice: number;

  /** Exit timestamp */
  exitTime: number;

  /** Position quantity */
  quantity: number;

  /** Gross P&L before commission */
  grossPnL: number;

  /** Total commission paid (entry + exit) */
  commission: number;

  /** Net P&L after commission */
  netPnL: number;

  /** Return percentage */
  returnPct: number;

  /** Holding period in bars */
  holdingPeriod: number;

  /** Reason for exit */
  exitReason: string;

  /** Grid level index (0-based) if this trade originated from a grid/DCA entry */
  gridLevel?: number;
}

/**
 * Extended equity point with drawdown info.
 */
export interface EquityPointExtended extends EquityPoint {
  /** Current drawdown from peak */
  drawdown: number;
  /** Current drawdown percentage */
  drawdownPct: number;
}

/**
 * Complete result from running the backtest engine.
 */
export interface BacktestEngineResult {
  /** Strategy identifier */
  strategyId: string;

  /** Parameters used for the backtest */
  params: BacktestParams;

  /** Calculated performance metrics */
  metrics: BacktestMetrics;

  /** List of all completed trades */
  trades: Trade[];

  /** Equity curve data points with drawdown */
  equityCurve: EquityPointExtended[];

  /** Final capital after backtest */
  finalCapital: number;

  /** Start date of the data */
  startDate: number;

  /** End date of the data */
  endDate: number;

  /** Total number of bars processed */
  totalBars: number;

  /** Whether a final position was force-closed at end */
  finalPositionClosed: boolean;
}

/**
 * Strategy interface specifically for the backtest engine.
 * Strategies implement this to generate signals synchronously
 * from pre-calculated indicator values.
 */
export interface Strategy {
  /** Unique strategy identifier */
  id: string;

  /** Human-readable strategy name */
  name: string;

  /**
   * Generate a trading signal based on current bar and indicators.
   *
   * @param bar - Current OHLC bar
   * @param indicators - Pre-calculated indicator values for this bar
   * @param position - Current open position (if any)
   * @returns Trading signal
   */
  generateSignal(
    bar: OHLC,
    indicators: IndicatorState,
    position: Position | null
  ): Signal;

  /**
   * Optional Kelly criterion parameters for position sizing.
   * If provided and positionSizing is KELLY, these will be used.
   */
  kellyParams?: KellyParams;
}
