/**
 * Hidden Markov Model regime classifier — Gaussian emissions,
 * Baum-Welch EM training, Viterbi decoding.
 *
 * Adapted from the J4nt4nCrypto / Hamilton (1989) regime-switching
 * literature. The premise: market returns are generated by a hidden
 * regime state (bull / bear / sideways / etc.) which itself follows
 * a Markov chain; the observed return at each time is drawn from a
 * regime-conditional Gaussian. Baum-Welch fits the transition matrix
 * + per-regime means/variances by maximum likelihood; Viterbi
 * recovers the most-likely sequence of hidden states.
 *
 * Honest scope:
 *
 *   This is a useful descriptive primitive — it tells you what regime
 *   structure best explains a return series, and where the regimes
 *   shift. It is NOT a trading edge generator. The original article's
 *   own conclusion: "Sharpe 0.2-0.5 after costs, often below buy-and-
 *   hold." Use HMM regime labels as a feature inside a richer
 *   strategy (regime-conditioned position sizing, regime-filtered
 *   entry signals) rather than as a standalone signal.
 *
 * Implementation notes:
 *
 *   - Forward / backward in log-space (logSumExp) for numerical
 *     stability on long series. Native-space arithmetic underflows
 *     past ~50 bars.
 *
 *   - Multiple random restarts (default 10) because Baum-Welch finds
 *     a LOCAL maximum of the likelihood. Best-of-N restart keeps the
 *     fit with the highest converged log-likelihood.
 *
 *   - Convergence by log-likelihood delta < 1e-4 between iterations,
 *     OR max iterations reached.
 *
 *   - Identifiability: HMM state labels are arbitrary (state 0 vs
 *     state 1 carries no meaning). We sort the final states by mean
 *     so the operator gets a consistent low-to-high ordering.
 */

const LOG_2PI = Math.log(2 * Math.PI);

export interface HmmInput {
  /** Observed series (e.g. log returns). At least 2× the state count
   *  recommended; under 30 observations is unreliable. */
  observations: number[];
  /** Number of hidden states. Default 3 (bull / sideways / bear). */
  nStates?: number;
  /** Number of random restarts. Each restart fits independently and
   *  the best by log-likelihood is kept. Default 10. */
  nRestarts?: number;
  /** Max Baum-Welch iterations per restart. Default 100. */
  maxIterations?: number;
  /** Convergence threshold on log-likelihood delta. Default 1e-4. */
  tolerance?: number;
  /** RNG seed for reproducibility. */
  seed?: number;
}

export interface HmmResult {
  /** Initial state distribution. Length nStates. */
  initialProbs: number[];
  /** Transition matrix. transitions[i][j] = P(j | i). nStates × nStates. */
  transitions: number[][];
  /** Per-state Gaussian emission means, sorted ascending. Length nStates. */
  means: number[];
  /** Per-state Gaussian emission variances. Length nStates. */
  variances: number[];
  /** Viterbi-decoded most-likely state sequence, length = observations.length. */
  stateSequence: number[];
  /** Final log-likelihood of the best fit. */
  logLikelihood: number;
  /** How many of the nRestarts converged within tolerance. */
  convergedRestarts: number;
  /** Iterations the best fit took to converge. */
  iterations: number;
  /** Stationary distribution implied by the transition matrix. */
  stationaryDistribution: number[];
  /** Per-state interpretation label based on mean (bear / sideways /
   *  bull for nStates=3, generic ascending for others). */
  stateLabels: string[];
}

function makeRng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

/** log( sum( exp(x_i) ) ) with the standard max-subtract trick to
 *  avoid overflow/underflow. */
function logSumExp(values: number[]): number {
  if (values.length === 0) return -Infinity;
  let max = -Infinity;
  for (const v of values) if (v > max) max = v;
  if (!Number.isFinite(max)) return max;
  let sum = 0;
  for (const v of values) sum += Math.exp(v - max);
  return max + Math.log(sum);
}

/** log( N(x | mu, var) ) — Gaussian log-density in log-space. */
function logGaussianPdf(x: number, mu: number, variance: number): number {
  if (variance <= 0) return -Infinity;
  const diff = x - mu;
  return -0.5 * (LOG_2PI + Math.log(variance) + (diff * diff) / variance);
}

/** Initialize HMM params with random splits + observed-stat seeding.
 *  The means are sampled across the observed range; variances start
 *  at the observed variance scaled by 1/nStates (each regime is
 *  narrower than the full series). */
function randomInit(
  observations: number[],
  nStates: number,
  rng: () => number,
): { pi: number[]; A: number[][]; mu: number[]; sigma2: number[] } {
  const min = Math.min(...observations);
  const max = Math.max(...observations);
  const obsMean = observations.reduce((a, b) => a + b, 0) / observations.length;
  const obsVar =
    observations.reduce((a, b) => a + (b - obsMean) * (b - obsMean), 0) / observations.length;
  const safeVar = obsVar > 1e-12 ? obsVar : 1e-6;

  // Uniform initial state distribution + small jitter.
  const pi = new Array<number>(nStates);
  let piSum = 0;
  for (let i = 0; i < nStates; i++) {
    pi[i] = 1 + rng() * 0.1;
    piSum += pi[i]!;
  }
  for (let i = 0; i < nStates; i++) pi[i] = pi[i]! / piSum;

  // Transition matrix: identity-biased + jitter (regimes are sticky).
  const A: number[][] = [];
  for (let i = 0; i < nStates; i++) {
    const row = new Array<number>(nStates);
    let rowSum = 0;
    for (let j = 0; j < nStates; j++) {
      row[j] = i === j ? 5 + rng() : 0.5 + rng();
      rowSum += row[j]!;
    }
    for (let j = 0; j < nStates; j++) row[j] = row[j]! / rowSum;
    A.push(row);
  }

  // Means spread across observed range.
  const mu = new Array<number>(nStates);
  for (let i = 0; i < nStates; i++) {
    const t = (i + 0.5) / nStates;
    mu[i] = min + (max - min) * t + (rng() - 0.5) * safeVar;
  }

  // Variances start as a fraction of overall variance.
  const sigma2 = new Array<number>(nStates).fill(safeVar / Math.max(1, nStates));

  return { pi, A, mu, sigma2 };
}

interface FitResult {
  pi: number[];
  A: number[][];
  mu: number[];
  sigma2: number[];
  logLik: number;
  iterations: number;
  converged: boolean;
}

function fitOnce(
  observations: number[],
  nStates: number,
  maxIterations: number,
  tolerance: number,
  rng: () => number,
): FitResult {
  const T = observations.length;
  let { pi, A, mu, sigma2 } = randomInit(observations, nStates, rng);

  // Pre-compute log-A for forward pass.
  const computeLogA = (): number[][] =>
    A.map((row) => row.map((v) => (v > 0 ? Math.log(v) : -Infinity)));
  const computeLogPi = (): number[] => pi.map((v) => (v > 0 ? Math.log(v) : -Infinity));

  let lastLogLik = -Infinity;
  let converged = false;
  let iter = 0;

  for (iter = 0; iter < maxIterations; iter++) {
    // ============ E-STEP ============
    const logA = computeLogA();
    const logPi = computeLogPi();
    // log emission: logB[t][i] = log N(o_t | mu_i, sigma2_i)
    const logB: number[][] = new Array(T);
    for (let t = 0; t < T; t++) {
      logB[t] = new Array<number>(nStates);
      for (let i = 0; i < nStates; i++) {
        logB[t]![i] = logGaussianPdf(observations[t]!, mu[i]!, sigma2[i]!);
      }
    }

    // Forward: logAlpha[t][i] = log P(o_1..o_t, q_t=i)
    const logAlpha: number[][] = new Array(T);
    logAlpha[0] = new Array<number>(nStates);
    for (let i = 0; i < nStates; i++) {
      logAlpha[0]![i] = logPi[i]! + logB[0]![i]!;
    }
    for (let t = 1; t < T; t++) {
      logAlpha[t] = new Array<number>(nStates);
      for (let j = 0; j < nStates; j++) {
        const terms: number[] = [];
        for (let i = 0; i < nStates; i++) {
          terms.push(logAlpha[t - 1]![i]! + logA[i]![j]!);
        }
        logAlpha[t]![j] = logSumExp(terms) + logB[t]![j]!;
      }
    }
    const logLik = logSumExp(logAlpha[T - 1]!);

    // Backward: logBeta[t][i] = log P(o_{t+1}..o_T | q_t=i)
    const logBeta: number[][] = new Array(T);
    logBeta[T - 1] = new Array<number>(nStates).fill(0);
    for (let t = T - 2; t >= 0; t--) {
      logBeta[t] = new Array<number>(nStates);
      for (let i = 0; i < nStates; i++) {
        const terms: number[] = [];
        for (let j = 0; j < nStates; j++) {
          terms.push(logA[i]![j]! + logB[t + 1]![j]! + logBeta[t + 1]![j]!);
        }
        logBeta[t]![i] = logSumExp(terms);
      }
    }

    // gamma[t][i] = posterior P(q_t = i | O) in log-space then exp.
    const gamma: number[][] = new Array(T);
    for (let t = 0; t < T; t++) {
      gamma[t] = new Array<number>(nStates);
      const denom = logSumExp(
        Array.from({ length: nStates }, (_, i) => logAlpha[t]![i]! + logBeta[t]![i]!),
      );
      for (let i = 0; i < nStates; i++) {
        gamma[t]![i] = Math.exp(logAlpha[t]![i]! + logBeta[t]![i]! - denom);
      }
    }

    // xi[t][i][j] = posterior P(q_t=i, q_{t+1}=j | O). Aggregate sum
    // over t for the M-step transition update.
    const xiSum: number[][] = Array.from({ length: nStates }, () => new Array<number>(nStates).fill(0));
    for (let t = 0; t < T - 1; t++) {
      const denomTerms: number[] = [];
      for (let i = 0; i < nStates; i++) {
        for (let j = 0; j < nStates; j++) {
          denomTerms.push(
            logAlpha[t]![i]! + logA[i]![j]! + logB[t + 1]![j]! + logBeta[t + 1]![j]!,
          );
        }
      }
      const denom = logSumExp(denomTerms);
      for (let i = 0; i < nStates; i++) {
        for (let j = 0; j < nStates; j++) {
          const xi = Math.exp(
            logAlpha[t]![i]! + logA[i]![j]! + logB[t + 1]![j]! + logBeta[t + 1]![j]! - denom,
          );
          xiSum[i]![j] = (xiSum[i]![j] ?? 0) + xi;
        }
      }
    }

    // ============ M-STEP ============
    // Initial probs.
    pi = gamma[0]!.slice();

    // Transition matrix.
    for (let i = 0; i < nStates; i++) {
      let rowSum = 0;
      for (let j = 0; j < nStates; j++) rowSum += xiSum[i]![j]!;
      if (rowSum < 1e-12) {
        // Degenerate row — keep self-loop to avoid NaN.
        for (let j = 0; j < nStates; j++) A[i]![j] = i === j ? 1 : 0;
      } else {
        for (let j = 0; j < nStates; j++) A[i]![j] = xiSum[i]![j]! / rowSum;
      }
    }

    // Emission means + variances.
    for (let i = 0; i < nStates; i++) {
      let weightSum = 0;
      let meanNumer = 0;
      for (let t = 0; t < T; t++) {
        const w = gamma[t]![i]!;
        weightSum += w;
        meanNumer += w * observations[t]!;
      }
      if (weightSum < 1e-12) continue;
      const newMu = meanNumer / weightSum;
      let varNumer = 0;
      for (let t = 0; t < T; t++) {
        const diff = observations[t]! - newMu;
        varNumer += gamma[t]![i]! * diff * diff;
      }
      mu[i] = newMu;
      // Floor variance to keep emissions non-degenerate.
      sigma2[i] = Math.max(varNumer / weightSum, 1e-8);
    }

    if (Math.abs(logLik - lastLogLik) < tolerance) {
      converged = true;
      lastLogLik = logLik;
      break;
    }
    lastLogLik = logLik;
  }

  return { pi, A, mu, sigma2, logLik: lastLogLik, iterations: iter + 1, converged };
}

/** Viterbi decoding — most-likely state sequence given fitted params.
 *  Log-space implementation for numerical stability. */
function viterbi(
  observations: number[],
  pi: number[],
  A: number[][],
  mu: number[],
  sigma2: number[],
): number[] {
  const T = observations.length;
  const N = pi.length;
  if (T === 0) return [];

  const logA = A.map((row) => row.map((v) => (v > 0 ? Math.log(v) : -Infinity)));
  const logPi = pi.map((v) => (v > 0 ? Math.log(v) : -Infinity));

  const delta: number[][] = new Array(T);
  const psi: number[][] = new Array(T);
  delta[0] = new Array<number>(N);
  psi[0] = new Array<number>(N).fill(0);
  for (let i = 0; i < N; i++) {
    delta[0]![i] = logPi[i]! + logGaussianPdf(observations[0]!, mu[i]!, sigma2[i]!);
  }

  for (let t = 1; t < T; t++) {
    delta[t] = new Array<number>(N);
    psi[t] = new Array<number>(N);
    for (let j = 0; j < N; j++) {
      let bestVal = -Infinity;
      let bestI = 0;
      for (let i = 0; i < N; i++) {
        const v = delta[t - 1]![i]! + logA[i]![j]!;
        if (v > bestVal) {
          bestVal = v;
          bestI = i;
        }
      }
      delta[t]![j] = bestVal + logGaussianPdf(observations[t]!, mu[j]!, sigma2[j]!);
      psi[t]![j] = bestI;
    }
  }

  // Trace back.
  const path = new Array<number>(T);
  let bestLast = 0;
  let bestVal = -Infinity;
  for (let i = 0; i < N; i++) {
    if (delta[T - 1]![i]! > bestVal) {
      bestVal = delta[T - 1]![i]!;
      bestLast = i;
    }
  }
  path[T - 1] = bestLast;
  for (let t = T - 2; t >= 0; t--) {
    path[t] = psi[t + 1]![path[t + 1]!]!;
  }
  return path;
}

/** Sort states ascending by mean and return the permutation map. */
function sortStatesByMean(mu: number[]): number[] {
  return mu.map((_, i) => i).sort((a, b) => mu[a]! - mu[b]!);
}

/** Apply a state-index permutation to all HMM artifacts. */
function permuteHmm(
  pi: number[],
  A: number[][],
  mu: number[],
  sigma2: number[],
  states: number[],
  perm: number[],
): { pi: number[]; A: number[][]; mu: number[]; sigma2: number[]; states: number[] } {
  const invPerm = new Array<number>(perm.length);
  for (let i = 0; i < perm.length; i++) invPerm[perm[i]!] = i;
  const newPi = perm.map((p) => pi[p]!);
  const newMu = perm.map((p) => mu[p]!);
  const newSigma2 = perm.map((p) => sigma2[p]!);
  const newA: number[][] = perm.map((iSrc) =>
    perm.map((jSrc) => A[iSrc]![jSrc]!),
  );
  const newStates = states.map((s) => invPerm[s]!);
  return { pi: newPi, A: newA, mu: newMu, sigma2: newSigma2, states: newStates };
}

/** Stationary distribution: solve π A = π with sum(π) = 1.
 *  Iterative power method — converges fast for small matrices. */
function stationaryDistribution(A: number[][]): number[] {
  const N = A.length;
  let pi = new Array<number>(N).fill(1 / N);
  for (let iter = 0; iter < 1000; iter++) {
    const next = new Array<number>(N).fill(0);
    for (let j = 0; j < N; j++) {
      for (let i = 0; i < N; i++) next[j] = (next[j] ?? 0) + pi[i]! * A[i]![j]!;
    }
    let maxDelta = 0;
    for (let j = 0; j < N; j++) {
      maxDelta = Math.max(maxDelta, Math.abs(next[j]! - pi[j]!));
    }
    pi = next;
    if (maxDelta < 1e-9) break;
  }
  return pi;
}

function labelStates(means: number[]): string[] {
  // For 3 states use bear/sideways/bull; for other counts use generic
  // low/.../high. States are already sorted ascending by mean before
  // labeling, so index aligns.
  if (means.length === 3) return ["bear", "sideways", "bull"];
  if (means.length === 2) return ["bear", "bull"];
  return means.map((_, i) => `state_${i}`);
}

export function fitHmmRegime(input: HmmInput): HmmResult {
  const T = input.observations.length;
  const nStates = input.nStates ?? 3;
  if (T < 2 * nStates) {
    throw new Error(
      `fitHmmRegime: need at least ${2 * nStates} observations for ${nStates} states; got ${T}`,
    );
  }
  if (!(nStates >= 2)) {
    throw new Error("fitHmmRegime: nStates must be >= 2");
  }
  if (input.observations.some((v) => !Number.isFinite(v))) {
    throw new Error("fitHmmRegime: observations must all be finite numbers");
  }
  const nRestarts = input.nRestarts ?? 10;
  const maxIterations = input.maxIterations ?? 100;
  const tolerance = input.tolerance ?? 1e-4;
  const baseSeed = input.seed ?? 42;

  let best: FitResult | null = null;
  let convergedCount = 0;
  for (let r = 0; r < nRestarts; r++) {
    const rng = makeRng(baseSeed + r * 7919);
    const fit = fitOnce(input.observations, nStates, maxIterations, tolerance, rng);
    if (fit.converged) convergedCount++;
    if (best === null || fit.logLik > best.logLik) best = fit;
  }
  if (best === null) {
    throw new Error("fitHmmRegime: all restarts failed");
  }

  const states = viterbi(input.observations, best.pi, best.A, best.mu, best.sigma2);

  // Permute states by mean ascending so labels are stable.
  const perm = sortStatesByMean(best.mu);
  const sorted = permuteHmm(best.pi, best.A, best.mu, best.sigma2, states, perm);

  return {
    initialProbs: sorted.pi,
    transitions: sorted.A,
    means: sorted.mu,
    variances: sorted.sigma2,
    stateSequence: sorted.states,
    logLikelihood: best.logLik,
    convergedRestarts: convergedCount,
    iterations: best.iterations,
    stationaryDistribution: stationaryDistribution(sorted.A),
    stateLabels: labelStates(sorted.mu),
  };
}
